# network architecture

model_conf:
    embed_size: 256
    hidden_size: 512
    linear_units: 2048
    attention_heads: 4
    num_layers: 6
    dropout: 0.1
    self_attention_dropout_rate: 0.0

dataset_conf:
    filter_conf:
        token_max_length: 200
        token_min_length: 1
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 32

grad_clip: 5
accum_grad: 4
max_epoch: 240
log_interval: 100

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
